
/* Drop Tables */

DROP TABLE IF EXISTS ADEMPIERE.SFA_SYNCCOLUMN_TRL;
DROP TABLE IF EXISTS ADEMPIERE.SFA_SYNCCOLUMN;
DROP TABLE IF EXISTS ADEMPIERE.SF_SYNCMENU_TRL;
DROP TABLE IF EXISTS ADEMPIERE.SFA_SYNCMENU;
DROP TABLE IF EXISTS ADEMPIERE.SFA_SYNCTABLE_TRL;
DROP TABLE IF EXISTS ADEMPIERE.SFA_SYNCTABLE;
DROP TABLE IF EXISTS ADEMPIERE.SFA_USERDOCSEQUENCE;




/* Create Tables */

CREATE TABLE ADEMPIERE.SFA_SYNCCOLUMN
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_COLUMN_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	AD_REFERENCE_ID NUMERIC(10,0) NOT NULL,
	AD_REFERENCE_VALUE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	AD_VAL_RULE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	CALLOUT VARCHAR(255) DEFAULT 'NULL::character varying',
	COLUMNNAME VARCHAR(30) NOT NULL,
	COLUMNSQL VARCHAR(2000) DEFAULT 'NULL::character varying',
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	DEFAULTVALUE VARCHAR(2000) DEFAULT 'NULL::character varying',
	DESCRIPTION VARCHAR(255) DEFAULT 'NULL::character varying',
	FIELDLENGTH NUMERIC(10,0) DEFAULT NULL::numeric,
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISALWAYSUPDATEABLE CHAR(1) DEFAULT '''N''::bpchar' NOT NULL,
	ISENCRYPTED CHAR(1) DEFAULT '''N''::bpchar',
	ISIDENTIFIER CHAR(1) NOT NULL,
	ISKEY CHAR(1) NOT NULL,
	ISMANDATORY CHAR(1) NOT NULL,
	ISPARENT CHAR(1) NOT NULL,
	ISSELECTIONCOLUMN CHAR(1) NOT NULL,
	ISUPDATEABLE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	SELECTIONSEQNO NUMERIC(10,0) DEFAULT NULL::numeric,
	SEQNO NUMERIC(10,0) DEFAULT NULL::numeric,
	SFA_SYNCCOLUMN_ID NUMERIC(10,0) NOT NULL,
	SFA_SYNCTABLE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_synccolumn_key PRIMARY KEY (SFA_SYNCCOLUMN_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SFA_SYNCCOLUMN_TRL
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_LANGUAGE VARCHAR(6) NOT NULL,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISTRANSLATED CHAR(1) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	SFA_SYNCCOLUMN_ID NUMERIC(10,0) DEFAULT NULL::numeric NOT NULL,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_synccolumn_trl_key PRIMARY KEY (AD_LANGUAGE, SFA_SYNCCOLUMN_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SFA_SYNCMENU
(
	ACTION CHAR(1) DEFAULT 'NULL::bpchar',
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_FORM_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	AD_PROCESS_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	DEPLOYMENTTYPE CHAR(1) DEFAULT 'NULL::bpchar',
	DESCRIPTION VARCHAR(255) DEFAULT 'NULL::character varying',
	ERRIMGURL VARCHAR(60) DEFAULT 'NULL::character varying',
	GROUPBYCLAUSE VARCHAR(255) DEFAULT 'NULL::character varying',
	IMAGEURL VARCHAR(120) DEFAULT 'NULL::character varying',
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISINSERTRECORD CHAR(1) DEFAULT 'NULL::bpchar',
	ISREADWRITE CHAR(1) DEFAULT 'NULL::bpchar',
	ISSUMMARY CHAR(1) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	ORDERBYCLAUSE VARCHAR(2000) DEFAULT 'NULL::character varying',
	SFA_SYNCMENU_ID NUMERIC(10,0) NOT NULL,
	SFA_SYNCTABLE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	WHERECLAUSE VARCHAR(2000) DEFAULT 'NULL::character varying',
	AD_RULEBEFORE_ID NUMERIC(10,0),
	AD_RULEAFTER_ID NUMERIC(10,0),
	WS_WEBSERVICETYPE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	CONSTRAINT sf_syncmenu_key PRIMARY KEY (SFA_SYNCMENU_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SFA_SYNCTABLE
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	AD_RULE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	AD_TABLE_ID NUMERIC(10,0) DEFAULT NULL::numeric,
	COPYCOLUMNSFROMTABLE CHAR(1) DEFAULT 'NULL::bpchar',
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT 'NULL::character varying',
	GENERATESCRIPTFROMTABLE CHAR(1) DEFAULT 'NULL::bpchar',
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISDELETEABLE CHAR(1) DEFAULT 'NULL::bpchar',
	ISVIEW CHAR(1) DEFAULT 'NULL::bpchar',
	NAME VARCHAR(60) NOT NULL,
	SFA_SYNCTABLE_ID NUMERIC(10,0) NOT NULL,
	TABLENAME VARCHAR(40) NOT NULL,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_synctable_key PRIMARY KEY (SFA_SYNCTABLE_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SFA_SYNCTABLE_TRL
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_LANGUAGE VARCHAR(6) NOT NULL,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISTRANSLATED CHAR(1) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	SFA_SYNCTABLE_ID NUMERIC(10,0) DEFAULT NULL::numeric NOT NULL,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_synctable_trl_key PRIMARY KEY (AD_LANGUAGE, SFA_SYNCTABLE_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SFA_USERDOCSEQUENCE
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	AD_SEQUENCE_ID NUMERIC(10,0) NOT NULL,
	C_DOCTYPE_ID NUMERIC(10,0) NOT NULL,
	AD_USER_ID NUMERIC(10,0) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_userdocsequence_key PRIMARY KEY (AD_SEQUENCE_ID, C_DOCTYPE_ID, AD_USER_ID)
) WITHOUT OIDS;


CREATE TABLE ADEMPIERE.SF_SYNCMENU_TRL
(
	AD_CLIENT_ID NUMERIC(10,0) NOT NULL,
	AD_LANGUAGE VARCHAR(6) NOT NULL,
	AD_ORG_ID NUMERIC(10,0) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CREATEDBY NUMERIC(10,0) NOT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT 'NULL::character varying',
	ISACTIVE CHAR(1) DEFAULT '''Y''::bpchar' NOT NULL,
	ISTRANSLATED CHAR(1) DEFAULT 'NULL::bpchar',
	NAME VARCHAR(60) NOT NULL,
	SFA_SYNCMENU_ID NUMERIC(10,0) NOT NULL,
	UPDATED TIMESTAMP NOT NULL,
	UPDATEDBY NUMERIC(10,0) NOT NULL,
	CONSTRAINT sf_syncmenu_trl_key PRIMARY KEY (AD_LANGUAGE, SFA_SYNCMENU_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE ADEMPIERE.SFA_SYNCCOLUMN_TRL
	ADD CONSTRAINT FK_SF_SYNCCOLUMN_TRL_SF_SYNCCOLUMN FOREIGN KEY (SFA_SYNCCOLUMN_ID)
	REFERENCES ADEMPIERE.SFA_SYNCCOLUMN (SFA_SYNCCOLUMN_ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
;


ALTER TABLE ADEMPIERE.SF_SYNCMENU_TRL
	ADD CONSTRAINT FK_SF_SYNCMENU_TRL_SF_SYNCMENU FOREIGN KEY (SFA_SYNCMENU_ID)
	REFERENCES ADEMPIERE.SFA_SYNCMENU (SFA_SYNCMENU_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ADEMPIERE.SFA_SYNCCOLUMN
	ADD CONSTRAINT FK_SF_SYNCCOLUMN_SF_SYNCTABLE FOREIGN KEY (SFA_SYNCTABLE_ID)
	REFERENCES ADEMPIERE.SFA_SYNCTABLE (SFA_SYNCTABLE_ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
;


ALTER TABLE ADEMPIERE.SFA_SYNCMENU
	ADD CONSTRAINT FK_SF_SYNCMENU_SF_SYNCTABLE FOREIGN KEY (SFA_SYNCTABLE_ID)
	REFERENCES ADEMPIERE.SFA_SYNCTABLE (SFA_SYNCTABLE_ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
;


ALTER TABLE ADEMPIERE.SFA_SYNCTABLE_TRL
	ADD CONSTRAINT FK_SF_SYNCTABLE_TRL_SF_SYNCTABLE FOREIGN KEY (SFA_SYNCTABLE_ID)
	REFERENCES ADEMPIERE.SFA_SYNCTABLE (SFA_SYNCTABLE_ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;



