-- Oct 30, 2013 8:57:53 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_VehicleType (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_VehicleType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LoadCapacity NUMBER NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) NOT NULL, CONSTRAINT FTA_VehicleType_Key PRIMARY KEY (FTA_VehicleType_ID))
;

-- Oct 30, 2013 9:00:00 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_VehicleModel (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMBER(10) NOT NULL, FTA_VehicleModel_ID NUMBER(10) NOT NULL, FTA_VehicleType_ID NUMBER(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_VehicleModel_Key PRIMARY KEY (FTA_VehicleModel_ID))
;

-- Oct 30, 2013 9:00:06 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_VehicleBrand (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_VehicleBrand_Key PRIMARY KEY (FTA_VehicleBrand_ID))
;

-- Oct 30, 2013 9:00:13 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Vehicle (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMBER(10) DEFAULT NULL , FTA_Vehicle_ID NUMBER(10) NOT NULL, FTA_VehicleModel_ID NUMBER(10) DEFAULT NULL , FTA_VehicleType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Shipper_ID NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, VehiclePlate NVARCHAR2(60) NOT NULL, CONSTRAINT FTA_Vehicle_Key PRIMARY KEY (FTA_Vehicle_ID))
;

-- Oct 30, 2013 9:00:20 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_TechnicalFormLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Comments NVARCHAR2(2000) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_FarmDivision_ID NUMBER(10) NOT NULL, FTA_Farm_ID NUMBER(10) NOT NULL, FTA_Farming_ID NUMBER(10) NOT NULL, FTA_FarmingStage_ID NUMBER(10) NOT NULL, FTA_ObservationType_ID NUMBER(10) NOT NULL, FTA_TechnicalForm_ID NUMBER(10) NOT NULL, FTA_TechnicalFormLine_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_TechnicalFormLine_Key PRIMARY KEY (FTA_TechnicalFormLine_ID))
;

-- Oct 30, 2013 9:00:29 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_TechnicalForm (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Comments NVARCHAR2(2000) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus NVARCHAR2(2) DEFAULT 'DR', DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_Farm_ID NUMBER(10) DEFAULT NULL , FTA_TechnicalForm_ID NUMBER(10) NOT NULL, GenerateOrder CHAR(1) DEFAULT 'N', IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, SalesRep_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_TechnicalForm_Key PRIMARY KEY (FTA_TechnicalForm_ID))
;

-- Oct 30, 2013 9:00:35 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_SuggestedProduct (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Category_ID NUMBER(10) DEFAULT NULL , Comments NVARCHAR2(255) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DayFrom NUMBER DEFAULT NULL , DayTo NUMBER DEFAULT NULL , Dosage_Uom_ID NUMBER(10) DEFAULT NULL , FTA_FarmingStage_ID NUMBER(10) DEFAULT NULL , FTA_ObservationType_ID NUMBER(10) DEFAULT NULL , FTA_SuggestedProduct_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_Category_ID NUMBER(10) DEFAULT NULL , M_Product_ID NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, QtyDosage NUMBER DEFAULT NULL , SeqNo NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_SuggestedProduct_Key PRIMARY KEY (FTA_SuggestedProduct_ID))
;

-- Oct 30, 2013 9:00:41 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_RecordWeight (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, CreateFrom CHAR(1) DEFAULT NULL , C_UOM_ID NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_EntryTicket_ID NUMBER(10) NOT NULL, FTA_QualityAnalysis_ID NUMBER(10) NOT NULL, FTA_RecordWeight_ID NUMBER(10) NOT NULL, GrossWeight NUMBER NOT NULL, I_IsImported CHAR(1) DEFAULT NULL  CHECK (I_IsImported IN ('Y','N')), ImportWeight NUMBER DEFAULT NULL , InDate DATE DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), IsSOTrx CHAR(1) CHECK (IsSOTrx IN ('Y','N')) NOT NULL, NetWeight NUMBER NOT NULL, OutDate DATE DEFAULT NULL , PayWeight NUMBER DEFAULT NULL , Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, SelectionWeight CHAR(1) DEFAULT 'P', TareWeight NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WeightStatus CHAR(1) DEFAULT 'T', CONSTRAINT FTA_RecordWeight_Key PRIMARY KEY (FTA_RecordWeight_ID))
;

-- Oct 30, 2013 9:00:46 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_ReceptionCapacity (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_ReceptionCapacity_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Warehouse_ID NUMBER(10) NOT NULL, Qty NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValidFrom DATE NOT NULL, CONSTRAINT FTA_ReceptionCapacity_Key PRIMARY KEY (FTA_ReceptionCapacity_ID))
;

-- Oct 30, 2013 9:00:51 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_QualityAnalysis (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AnalysisType NVARCHAR2(2) DEFAULT 'QA' NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus NVARCHAR2(2) DEFAULT 'DR', DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_EntryTicket_ID NUMBER(10) NOT NULL, FTA_QualityAnalysis_ID NUMBER(10) NOT NULL, I_IsImported CHAR(1) DEFAULT NULL  CHECK (I_IsImported IN ('Y','N')), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), M_Product_ID NUMBER(10) DEFAULT NULL , Orig_QualityAnalysis_ID NUMBER(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), ProductStatus CHAR(1) DEFAULT 'A' NOT NULL, QualityAnalysis_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_QualityAnalysis_Key PRIMARY KEY (FTA_QualityAnalysis_ID))
;

-- Oct 30, 2013 9:00:57 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_ProductsToApply (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, C_UOM_ID NUMBER(10) NOT NULL, DateFrom DATE DEFAULT NULL , DateTo DATE DEFAULT NULL , Dosage_Uom_ID NUMBER(10) NOT NULL, FTA_ProductsToApply_ID NUMBER(10) NOT NULL, FTA_TechnicalForm_ID NUMBER(10) NOT NULL, FTA_TechnicalFormLine_ID NUMBER(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Qty NUMBER NOT NULL, QtyDosage NUMBER NOT NULL, QtySuggested NUMBER DEFAULT NULL , Suggested_Uom_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_ProductsToApply_Key PRIMARY KEY (FTA_ProductsToApply_ID))
;

-- Oct 30, 2013 9:01:02 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_PaymentRequest (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_Charge_ID NUMBER(10) DEFAULT NULL , C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(30) DEFAULT NULL , FTA_FarmerCredit_ID NUMBER(10) NOT NULL, FTA_FarmerLiquidation_ID NUMBER(10) DEFAULT NULL , FTA_PaymentRequest_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, PayAmt NUMBER NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_PaymentRequest_Key PRIMARY KEY (FTA_PaymentRequest_ID))
;

-- Oct 30, 2013 9:01:08 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_ObservationType (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_ObservationType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) NOT NULL, CONSTRAINT FTA_ObservationType_Key PRIMARY KEY (FTA_ObservationType_ID))
;

-- Oct 30, 2013 9:01:14 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_MobilizationGuide (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) DEFAULT NULL , C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(30) NOT NULL, FTA_Farming_ID NUMBER(10) NOT NULL, FTA_MobilizationGuide_ID NUMBER(10) NOT NULL, FTA_VehicleType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Warehouse_ID NUMBER(10) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), QtyToDeliver NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValidTo DATE DEFAULT NULL , CONSTRAINT FTA_MobilizationGuide_Key PRIMARY KEY (FTA_MobilizationGuide_ID))
;

-- Oct 30, 2013 9:01:19 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_InterestType (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, CalculationType CHAR(1) DEFAULT 'C' NOT NULL, C_Charge_ID NUMBER(10) DEFAULT NULL , C_DocTypeTarget_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_InterestType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, RateFixed CHAR(1) DEFAULT 'Y' CHECK (RateFixed IN ('Y','N')), Type NVARCHAR2(2) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(40) NOT NULL, CONSTRAINT FTA_InterestType_Key PRIMARY KEY (FTA_InterestType_ID))
;

-- Oct 30, 2013 9:01:24 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_InterestRate (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_InterestRate_ID NUMBER(10) NOT NULL, FTA_InterestType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Rate NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValidFrom DATE NOT NULL, CONSTRAINT FTA_InterestRate_Key PRIMARY KEY (FTA_InterestRate_ID))
;

-- Oct 30, 2013 9:01:30 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_FarmingStage (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Category_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DayFrom NUMBER NOT NULL, DayTo NUMBER NOT NULL, FTA_FarmingStage_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SeqNo NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) DEFAULT NULL , CONSTRAINT FTA_FarmingStage_Key PRIMARY KEY (FTA_FarmingStage_ID))
;

-- Oct 30, 2013 9:01:35 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Farming (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Area NUMBER NOT NULL, Category_ID NUMBER(10) NOT NULL, C_OrderLine_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EstimatedDate DATE DEFAULT NULL , EstimatedQty NUMBER DEFAULT NULL , EstimatedYield NUMBER DEFAULT NULL , FarmingValidate CHAR(1) DEFAULT NULL , FinancingType CHAR(1) NOT NULL, FTA_FarmDivision_ID NUMBER(10) NOT NULL, FTA_FarmerCredit_ID NUMBER(10) DEFAULT NULL , FTA_Farming_ID NUMBER(10) NOT NULL, GuideGenerate CHAR(1) DEFAULT NULL , HarvestEndDate DATE DEFAULT NULL , HarvestStartDate DATE DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) DEFAULT NULL  CHECK (IsValid IN ('Y','N')), MaxQty NUMBER DEFAULT NULL , PlantingCycle_ID NUMBER(10) NOT NULL, PlantingEndDate DATE DEFAULT NULL , PlantingStartDate DATE DEFAULT NULL , Qty NUMBER DEFAULT NULL , Re_EstimatedQty NUMBER DEFAULT NULL , StartDate DATE NOT NULL, Status CHAR(1) DEFAULT 'A' NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_Farming_Key PRIMARY KEY (FTA_Farming_ID))
;

-- Oct 30, 2013 9:01:49 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_FarmerLiquidationLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_FarmerLiquidation_ID NUMBER(10) NOT NULL, FTA_FarmerLiquidationLine_ID NUMBER(10) NOT NULL, FTA_RecordWeight_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, NetWeight NUMBER NOT NULL, PayWeight NUMBER NOT NULL, Price NUMBER NOT NULL, PriceList NUMBER DEFAULT NULL , Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, QualityAnalysis_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_FarmerLiquidationLine_Key PRIMARY KEY (FTA_FarmerLiquidationLine_ID))
;

-- Oct 30, 2013 9:01:54 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_FarmerLiquidation (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_ConversionType_ID NUMBER(10) DEFAULT NULL , C_Currency_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, C_Invoice_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_CategoryCalc_ID NUMBER(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMBER(10) NOT NULL, FTA_FarmerLiquidation_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) NOT NULL, NetWeight NUMBER NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_FarmerLiquidation_Key PRIMARY KEY (FTA_FarmerLiquidation_ID))
;

-- Oct 30, 2013 9:02:00 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_FarmerCredit (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, ApprovedAmt NUMBER DEFAULT NULL , ApprovedQty NUMBER DEFAULT NULL , Beneficiary_ID NUMBER(10) DEFAULT NULL , C_BPartner_ID NUMBER(10) NOT NULL, C_Charge_ID NUMBER(10) DEFAULT NULL , C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, CreditType CHAR(1) NOT NULL, C_UOM_ID NUMBER(10) DEFAULT NULL , DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) DEFAULT NULL , FarmingAlloc CHAR(1) DEFAULT NULL , FTA_CreditAct_ID NUMBER(10) DEFAULT NULL , FTA_CreditDefinition_ID NUMBER(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMBER(10) NOT NULL, GenerateBillOfEx CHAR(1) DEFAULT NULL , GenerateOrder CHAR(1) DEFAULT 'N', IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) DEFAULT NULL , Parent_FarmerCredit_ID NUMBER(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Qty NUMBER NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_FarmerCredit_Key PRIMARY KEY (FTA_FarmerCredit_ID))
;

-- Oct 30, 2013 9:02:05 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_FarmDivision (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Area NUMBER NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_FarmDivision_ID NUMBER(10) NOT NULL, FTA_Farm_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_FarmDivision_Key PRIMARY KEY (FTA_FarmDivision_ID))
;

-- Oct 30, 2013 9:02:10 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Farm (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Area NUMBER NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_BPartner_Location_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FarmType CHAR(1) NOT NULL, FrontierEast NVARCHAR2(255) DEFAULT NULL , FrontierNorth NVARCHAR2(255) DEFAULT NULL , FrontierSouth NVARCHAR2(255) DEFAULT NULL , FrontierWest NVARCHAR2(255) DEFAULT NULL , FTA_Farm_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) CHECK (IsValid IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_Farm_Key PRIMARY KEY (FTA_Farm_ID))
;

-- Oct 30, 2013 9:02:14 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Fact (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Table_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_CreditDefinition_ID NUMBER(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMBER(10) NOT NULL, FTA_Fact_ID NUMBER(10) NOT NULL, FTA_FarmerCredit_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCreditFactManual CHAR(1) DEFAULT NULL  CHECK (IsCreditFactManual IN ('Y','N')), Line_ID NUMBER(10) DEFAULT NULL , Record_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_Fact_Key PRIMARY KEY (FTA_Fact_ID))
;

-- Oct 30, 2013 9:02:20 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_EntryTicketGuide (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Ext_Guide NVARCHAR2(60) DEFAULT NULL , FTA_EntryTicketGuide_ID NUMBER(10) NOT NULL, FTA_EntryTicket_ID NUMBER(10) DEFAULT NULL , FTA_MobilizationGuide_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_EntryTicketGuide_Key PRIMARY KEY (FTA_EntryTicketGuide_ID))
;

-- Oct 30, 2013 9:02:26 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_EntryTicket (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus NVARCHAR2(2) DEFAULT 'DR', DocumentNo NVARCHAR2(60) DEFAULT NULL , Ext_Guide NVARCHAR2(60) DEFAULT NULL , FTA_Driver_ID NUMBER(10) NOT NULL, FTA_EntryTicket_ID NUMBER(10) NOT NULL, FTA_MobilizationGuide_ID NUMBER(10) NOT NULL, FTA_Vehicle_ID NUMBER(10) NOT NULL, I_IsImported CHAR(1) DEFAULT NULL  CHECK (I_IsImported IN ('Y','N')), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), M_Shipper_ID NUMBER(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), ReferenceNo NVARCHAR2(60) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_EntryTicket_Key PRIMARY KEY (FTA_EntryTicket_ID))
;

-- Oct 30, 2013 9:02:31 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Driver (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_Driver_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Shipper_ID NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) NOT NULL, CONSTRAINT FTA_Driver_Key PRIMARY KEY (FTA_Driver_ID))
;

-- Oct 30, 2013 9:02:37 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CreditDefinitionLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, C_Charge_ID NUMBER(10) DEFAULT NULL , C_ChargeType_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, C_UOM_ID NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_CDL_Category_ID NUMBER(10) NOT NULL, FTA_CreditDefinition_ID NUMBER(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCreditLimitExceeded CHAR(1) DEFAULT 'N' CHECK (IsCreditLimitExceeded IN ('Y','N')), Line NUMBER(10) NOT NULL, M_Product_Category_ID NUMBER(10) DEFAULT NULL , M_Product_ID NUMBER(10) DEFAULT NULL , Price NUMBER NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Qty NUMBER DEFAULT 1 NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_CreditDefinitionLine_Key PRIMARY KEY (FTA_CreditDefinitionLine_ID))
;

-- Oct 30, 2013 9:02:43 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CreditDefinition (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, Category_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_CreditDefinition_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, M_PriceList_ID NUMBER(10) NOT NULL, PlantingCycle_ID NUMBER(10) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_CreditDefinition_Key PRIMARY KEY (FTA_CreditDefinition_ID))
;

-- Oct 30, 2013 9:02:48 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CreditAct (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) DEFAULT NULL , FTA_CreditAct_ID NUMBER(10) NOT NULL, GenerateBillOfEx CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_CreditAct_Key PRIMARY KEY (FTA_CreditAct_ID))
;

-- Oct 30, 2013 9:02:53 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CDL_CategoryInterest (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, FTA_CDL_Category_ID NUMBER(10) NOT NULL, FTA_InterestType_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_CDL_CategoryInterest_Key PRIMARY KEY (FTA_CDL_Category_ID, FTA_InterestType_ID))
;

-- Oct 30, 2013 9:02:57 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CDL_Category (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , FTA_CDL_Category_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(40) NOT NULL, CONSTRAINT FTA_CDL_Category_Key PRIMARY KEY (FTA_CDL_Category_ID))
;

-- Oct 30, 2013 9:03:03 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_CategoryCalc (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Rule_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EventType NVARCHAR2(2) NOT NULL, FTA_CategoryCalc_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMBER(10) NOT NULL, Name NVARCHAR2(60) NOT NULL, StdPrecision NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_CategoryCalc_Key PRIMARY KEY (FTA_CategoryCalc_ID))
;

-- Oct 30, 2013 9:03:08 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_BillOfExchange (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amt NUMBER NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_BPartner_Location_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(30) NOT NULL, FTA_BillOfExchange_ID NUMBER(10) NOT NULL, FTA_FarmerCredit_ID NUMBER(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N')), Status CHAR(1) DEFAULT 'G' NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValidTo DATE DEFAULT NULL , CONSTRAINT FTA_BillOfExchange_Key PRIMARY KEY (FTA_BillOfExchange_ID))
;

-- Oct 30, 2013 9:03:29 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_AllocationLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AllocationNo NUMBER DEFAULT NULL , Amount NUMBER NOT NULL, C_BPartner_ID NUMBER(10) DEFAULT NULL , C_CashLine_ID NUMBER(10) DEFAULT NULL , C_Invoice_ID NUMBER(10) NOT NULL, C_Order_ID NUMBER(10) DEFAULT NULL , C_Payment_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE DEFAULT NULL , DiscountAmt NUMBER NOT NULL, FTA_Allocation_ID NUMBER(10) NOT NULL, FTA_AllocationLine_ID NUMBER(10) NOT NULL, FTA_FarmerLiquidation_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, OverUnderAmt NUMBER DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WriteOffAmt NUMBER NOT NULL, CONSTRAINT FTA_AllocationLine_Key PRIMARY KEY (FTA_AllocationLine_ID))
;

-- Oct 30, 2013 9:03:35 PM VET
-- Farming Technical Assistance
CREATE TABLE FTA_Allocation (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, ApprovalAmt NUMBER NOT NULL, C_Currency_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateDoc DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus NVARCHAR2(2) DEFAULT 'DR' NOT NULL, DocumentNo NVARCHAR2(60) NOT NULL, FTA_Allocation_ID NUMBER(10) NOT NULL, FTA_FarmerCredit_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT FTA_Allocation_Key PRIMARY KEY (FTA_Allocation_ID))
;

