-- Apr 28, 2014 11:28:58 AM VET
-- Farming Technical Assistance
UPDATE AD_Process SET JasperReport='attachment:inf_Ticket_Record_Weight.jrxml',Updated=TO_TIMESTAMP('2014-04-28 11:28:58','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_ID=53551
;

-- Apr 28, 2014 11:29:26 AM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,DefaultValue,Description,EntityType,FieldLength,Help,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,577,0,53551,54728,11,'StdPrecision',TO_TIMESTAMP('2014-04-28 11:29:23','YYYY-MM-DD HH24:MI:SS'),100,'0','Rule for rounding  calculated amounts','ECA02',22,'The Standard Precision defines the number of decimal places that amounts will be rounded to for accounting transactions and documents.','Y','Y','Y','N','Standard Precision',165,TO_TIMESTAMP('2014-04-28 11:29:23','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 11:29:26 AM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54728 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 11:30:05 AM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,290,0,53551,54729,10,'DocumentNo',TO_TIMESTAMP('2014-04-28 11:30:03','YYYY-MM-DD HH24:MI:SS'),100,'Document sequence number of the document','ECA02',30,'The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Y','Y','N','N','Document No',175,TO_TIMESTAMP('2014-04-28 11:30:03','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 11:30:05 AM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54729 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 11:30:13 AM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET SeqNo=45,Updated=TO_TIMESTAMP('2014-04-28 11:30:13','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54729
;

-- Apr 28, 2014 12:05:43 PM VET
-- Farming Technical Assistance
DELETE FROM AD_Process_Para_Trl WHERE AD_Process_Para_ID=54729
;

-- Apr 28, 2014 12:05:43 PM VET
-- Farming Technical Assistance
DELETE FROM AD_Process_Para WHERE AD_Process_Para_ID=54729
;

-- Apr 28, 2014 12:06:24 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,EntityType,FieldLength,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,56135,0,53551,54730,19,'FTA_RecordWeight_ID',TO_TIMESTAMP('2014-04-28 12:06:11','YYYY-MM-DD HH24:MI:SS'),100,'ECA02',0,'Y','Y','N','N','Record Weight',175,TO_TIMESTAMP('2014-04-28 12:06:11','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 12:06:24 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54730 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 12:07:11 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET SeqNo=45,Updated=TO_TIMESTAMP('2014-04-28 12:07:11','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54730
;

-- Apr 28, 2014 12:11:45 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Val_Rule (AD_Client_ID,AD_Org_ID,AD_Val_Rule_ID,Code,Created,CreatedBy,EntityType,IsActive,Name,Type,Updated,UpdatedBy) VALUES (0,0,52349,'FTA_RecordWeight.OperationType = @OperationType@',TO_TIMESTAMP('2014-04-28 12:11:43','YYYY-MM-DD HH24:MI:SS'),100,'ECA02','Y','FTA_RecordWeight in Operation Type','S',TO_TIMESTAMP('2014-04-28 12:11:43','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 12:11:53 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET AD_Val_Rule_ID=52349, SeqNo=22,Updated=TO_TIMESTAMP('2014-04-28 12:11:53','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54730
;

-- Apr 28, 2014 2:02:10 PM VET
-- Farming Technical Assistance
UPDATE AD_Val_Rule SET Code='FTA_RecordWeight.OperationType = ''@OperationType@''',Updated=TO_TIMESTAMP('2014-04-28 14:02:10','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Val_Rule_ID=52349
;

-- Apr 28, 2014 2:09:12 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,AD_Val_Rule_ID,ColumnName,Created,CreatedBy,EntityType,FieldLength,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,56135,0,53584,54731,19,52349,'FTA_RecordWeight_ID',TO_TIMESTAMP('2014-04-28 14:09:03','YYYY-MM-DD HH24:MI:SS'),100,'ECA02',0,'Y','Y','N','N','Record Weight',165,TO_TIMESTAMP('2014-04-28 14:09:03','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 2:09:12 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54731 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 2:10:24 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET SeqNo=22,Updated=TO_TIMESTAMP('2014-04-28 14:10:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54731
;

-- Apr 28, 2014 2:10:51 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,577,0,53584,54732,11,'StdPrecision',TO_TIMESTAMP('2014-04-28 14:10:46','YYYY-MM-DD HH24:MI:SS'),100,'Rule for rounding  calculated amounts','ECA02',22,'The Standard Precision defines the number of decimal places that amounts will be rounded to for accounting transactions and documents.','Y','Y','N','N','Standard Precision',165,TO_TIMESTAMP('2014-04-28 14:10:46','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 2:10:51 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54732 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 2:11:14 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET DefaultValue='0', IsMandatory='Y',Updated=TO_TIMESTAMP('2014-04-28 14:11:14','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54732
;

-- Apr 28, 2014 2:12:20 PM VET
-- Farming Technical Assistance
UPDATE AD_Process SET JasperReport='attachment:inf_Guide_Record_Weight.jrxml',Updated=TO_TIMESTAMP('2014-04-28 14:12:20','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_ID=53584
;

-- Apr 28, 2014 3:27:22 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,577,0,53604,54733,11,'StdPrecision',TO_TIMESTAMP('2014-04-28 15:27:19','YYYY-MM-DD HH24:MI:SS'),100,'Rule for rounding  calculated amounts','ECA02',22,'The Standard Precision defines the number of decimal places that amounts will be rounded to for accounting transactions and documents.','Y','Y','N','N','Standard Precision',165,TO_TIMESTAMP('2014-04-28 15:27:19','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 3:27:22 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54733 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 3:28:07 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,AD_Val_Rule_ID,ColumnName,Created,CreatedBy,EntityType,FieldLength,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,56135,0,53604,54734,19,52349,'FTA_RecordWeight_ID',TO_TIMESTAMP('2014-04-28 15:28:03','YYYY-MM-DD HH24:MI:SS'),100,'ECA02',0,'Y','Y','N','N','Record Weight',175,TO_TIMESTAMP('2014-04-28 15:28:03','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 3:28:07 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54734 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 3:28:24 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET SeqNo=22,Updated=TO_TIMESTAMP('2014-04-28 15:28:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54734
;

-- Apr 28, 2014 3:31:36 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET DefaultValue='0', IsMandatory='Y',Updated=TO_TIMESTAMP('2014-04-28 15:31:36','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54733
;

-- Apr 28, 2014 3:56:27 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,AD_Val_Rule_ID,ColumnName,Created,CreatedBy,EntityType,FieldLength,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,56135,0,53606,54735,19,52349,'FTA_RecordWeight_ID',TO_TIMESTAMP('2014-04-28 15:56:24','YYYY-MM-DD HH24:MI:SS'),100,'ECA02',0,'Y','Y','N','N','Record Weight',165,TO_TIMESTAMP('2014-04-28 15:56:24','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 3:56:27 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54735 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 3:56:30 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET SeqNo=22,Updated=TO_TIMESTAMP('2014-04-28 15:56:30','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54735
;

-- Apr 28, 2014 3:56:44 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para (AD_Client_ID,AD_Element_ID,AD_Org_ID,AD_Process_ID,AD_Process_Para_ID,AD_Reference_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsCentrallyMaintained,IsMandatory,IsRange,Name,SeqNo,Updated,UpdatedBy) VALUES (0,577,0,53606,54736,11,'StdPrecision',TO_TIMESTAMP('2014-04-28 15:56:42','YYYY-MM-DD HH24:MI:SS'),100,'Rule for rounding  calculated amounts','ECA02',22,'The Standard Precision defines the number of decimal places that amounts will be rounded to for accounting transactions and documents.','Y','Y','N','N','Standard Precision',165,TO_TIMESTAMP('2014-04-28 15:56:42','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 28, 2014 3:56:44 PM VET
-- Farming Technical Assistance
INSERT INTO AD_Process_Para_Trl (AD_Language,AD_Process_Para_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Process_Para_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Process_Para t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Process_Para_ID=54736 AND NOT EXISTS (SELECT * FROM AD_Process_Para_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Process_Para_ID=t.AD_Process_Para_ID)
;

-- Apr 28, 2014 3:56:51 PM VET
-- Farming Technical Assistance
UPDATE AD_Process_Para SET DefaultValue='0', IsMandatory='Y',Updated=TO_TIMESTAMP('2014-04-28 15:56:51','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Process_Para_ID=54736
;

