-- Aug 22, 2014 11:20:51 AM VET
-- FTA
CREATE TABLE FTA_Allocation (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, ApprovalAmt NUMERIC NOT NULL, C_AllocationHdr_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) NOT NULL, FTA_Allocation_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsCreditFactPosted CHAR(1) DEFAULT 'N' CHECK (IsCreditFactPosted IN ('Y','N')), Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Allocation_Key PRIMARY KEY (FTA_Allocation_ID))
;

-- Aug 22, 2014 11:20:59 AM VET
-- FTA
CREATE TABLE FTA_AllocationLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AllocationNo NUMERIC DEFAULT NULL , Amount NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , C_CashLine_ID NUMERIC(10) DEFAULT NULL , C_Invoice_ID NUMERIC(10) DEFAULT NULL , C_Order_ID NUMERIC(10) DEFAULT NULL , C_Payment_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP DEFAULT NULL , DiscountAmt NUMERIC NOT NULL, FTA_Allocation_ID NUMERIC(10) NOT NULL, FTA_AllocationLine_ID NUMERIC(10) NOT NULL, FTA_FarmerLiquidation_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, OverUnderAmt NUMERIC DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WriteOffAmt NUMERIC NOT NULL, CONSTRAINT FTA_AllocationLine_Key PRIMARY KEY (FTA_AllocationLine_ID))
;

-- Aug 22, 2014 11:21:05 AM VET
-- FTA
CREATE TABLE FTA_AttributeReport (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_AttributeReport_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_AttributeReport_Key PRIMARY KEY (FTA_AttributeReport_ID))
;

-- Aug 22, 2014 11:21:11 AM VET
-- FTA
CREATE TABLE FTA_AttributeReportLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_AttributeReport_ID NUMERIC(10) NOT NULL, FTA_AttributeReportLine_ID NUMERIC(10) NOT NULL, FTA_CategoryCalcGroup_ID NUMERIC(10) DEFAULT NULL , FTA_CategoryCalc_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Attribute_ID NUMERIC(10) DEFAULT NULL , M_AttributeSet_ID NUMERIC(10) DEFAULT NULL , PrintName VARCHAR(60) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_AttributeReportLine_Key PRIMARY KEY (FTA_AttributeReportLine_ID))
;

-- Aug 22, 2014 11:21:19 AM VET
-- FTA
CREATE TABLE FTA_BillOfExchange (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_BPartner_Location_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, C_Invoice_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(30) NOT NULL, FTA_BillOfExchange_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , FTA_FC_PaySchedule_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Status CHAR(1) DEFAULT 'G' NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValidTo TIMESTAMP DEFAULT NULL , CONSTRAINT FTA_BillOfExchange_Key PRIMARY KEY (FTA_BillOfExchange_ID))
;

-- Aug 22, 2014 11:21:24 AM VET
-- FTA
CREATE TABLE FTA_CategoryCalc (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Rule_ID NUMERIC(10) NOT NULL, CopyFrom CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EventType VARCHAR(2) NOT NULL, FTA_CategoryCalcGroup_ID NUMERIC(10) DEFAULT NULL , FTA_CategoryCalc_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsPayWeight CHAR(1) DEFAULT 'N' CHECK (IsPayWeight IN ('Y','N')), M_AttributeSetInstance_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, SeqNo NUMERIC(10) DEFAULT NULL , StdPrecision NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CategoryCalc_Key PRIMARY KEY (FTA_CategoryCalc_ID))
;

-- Aug 22, 2014 11:21:30 AM VET
-- FTA
CREATE TABLE FTA_CategoryCalcFilter (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AttributeValueType CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CategoryCalcFilter_ID NUMERIC(10) NOT NULL, FTA_CategoryCalc_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsLot CHAR(1) DEFAULT 'N' CHECK (IsLot IN ('Y','N')), M_Attribute_ID NUMERIC(10) DEFAULT NULL , M_AttributeValue2_ID NUMERIC(10) DEFAULT NULL , M_AttributeValue_ID NUMERIC(10) DEFAULT NULL , PlantingCycle_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) DEFAULT NULL , Value2 VARCHAR(60) DEFAULT NULL , ValueNumber NUMERIC DEFAULT NULL , ValueNumber2 NUMERIC DEFAULT NULL , CONSTRAINT FTA_CategoryCalcFilter_Key PRIMARY KEY (FTA_CategoryCalcFilter_ID))
;

-- Aug 22, 2014 11:21:35 AM VET
-- FTA
CREATE TABLE FTA_CategoryCalcGroup (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CategoryCalcGroup_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT FTA_CategoryCalcGroup_Key PRIMARY KEY (FTA_CategoryCalcGroup_ID))
;

-- Aug 22, 2014 11:21:42 AM VET
-- FTA
CREATE TABLE FTA_CDL_Category (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CDL_Category_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, CONSTRAINT FTA_CDL_Category_Key PRIMARY KEY (FTA_CDL_Category_ID))
;

-- Aug 22, 2014 11:21:47 AM VET
-- FTA
CREATE TABLE FTA_CDL_CategoryInterest (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CDL_Category_ID NUMERIC(10) NOT NULL, FTA_InterestType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CDL_CategoryInterest_Key PRIMARY KEY (FTA_CDL_Category_ID, FTA_InterestType_ID))
;

-- Aug 22, 2014 11:21:53 AM VET
-- FTA
CREATE TABLE FTA_CDL_Report (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CDL_Report_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CDL_Report_Key PRIMARY KEY (FTA_CDL_Report_ID))
;

-- Aug 22, 2014 11:22:00 AM VET
-- FTA
CREATE TABLE FTA_CDL_ReportGroup (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CDL_ReportGroup_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, PrintName VARCHAR(60) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CDL_ReportGroup_Key PRIMARY KEY (FTA_CDL_ReportGroup_ID))
;

-- Aug 22, 2014 11:22:06 AM VET
-- FTA
CREATE TABLE FTA_CDL_ReportLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CDL_Category_ID NUMERIC(10) DEFAULT NULL , FTA_CDL_ReportGroup_ID NUMERIC(10) DEFAULT NULL , FTA_CDL_Report_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, PrintName VARCHAR(60) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CDL_ReportLine_Key PRIMARY KEY (FTA_CDL_Category_ID, FTA_CDL_Report_ID))
;

-- Aug 22, 2014 11:22:12 AM VET
-- FTA
CREATE TABLE FTA_Chute (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_Chute_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsDefault CHAR(1) DEFAULT NULL CHECK (IsDefault IN ('Y','N')), M_Locator_ID NUMERIC(10) DEFAULT NULL , M_Warehouse_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Chute_Key PRIMARY KEY (FTA_Chute_ID))
;

-- Aug 22, 2014 11:22:20 AM VET
-- FTA
CREATE TABLE FTA_CreditAct (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, ApprovedAmt NUMERIC DEFAULT NULL , ApprovedQty NUMERIC DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , FTA_CreditAct_ID NUMERIC(10) NOT NULL, GenerateBillOfEx CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CreditAct_Key PRIMARY KEY (FTA_CreditAct_ID))
;

-- Aug 22, 2014 11:22:32 AM VET
-- FTA
CREATE TABLE FTA_CreditDefinition (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, Category_ID NUMERIC(10) DEFAULT NULL , C_DocTypeClosedAP_ID NUMERIC(10) DEFAULT NULL , C_DocTypeClosedAR_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, CopyFrom CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CreditType CHAR(1) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, M_PriceList_ID NUMERIC(10) NOT NULL, PlantingCycle_ID NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CreditDefinition_Key PRIMARY KEY (FTA_CreditDefinition_ID))
;

-- Aug 22, 2014 11:22:39 AM VET
-- FTA
CREATE TABLE FTA_CreditDefinitionLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_ChargeType_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CDL_Category_ID NUMERIC(10) NOT NULL, FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsDistributionLine CHAR(1) DEFAULT 'N' CHECK (IsDistributionLine IN ('Y','N')), IsExceedCreditLimit CHAR(1) DEFAULT 'N' CHECK (IsExceedCreditLimit IN ('Y','N')), Line NUMERIC(10) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , Price NUMERIC NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Qty NUMERIC DEFAULT 1 NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_CreditDefinitionLine_Key PRIMARY KEY (FTA_CreditDefinitionLine_ID))
;

-- Aug 22, 2014 11:24:04 AM VET
-- FTA
CREATE TABLE FTA_Driver (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_Driver_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Shipper_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT FTA_Driver_Key PRIMARY KEY (FTA_Driver_ID))
;

-- Aug 22, 2014 11:24:10 AM VET
-- FTA
CREATE TABLE FTA_EntryTicket (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10) DEFAULT NULL , C_OrderLine_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus VARCHAR(2) DEFAULT 'DR', DocumentNo VARCHAR(60) DEFAULT NULL , DocumentPrint CHAR(1) DEFAULT NULL , Ext_Guide VARCHAR(60) DEFAULT NULL , FTA_Driver_ID NUMERIC(10) NOT NULL, FTA_EntryTicket_ID NUMERIC(10) NOT NULL, FTA_LoadOrder_ID NUMERIC(10) DEFAULT NULL , FTA_MobilizationGuide_ID NUMERIC(10) DEFAULT NULL , FTA_Vehicle_ID NUMERIC(10) NOT NULL, I_IsImported CHAR(1) DEFAULT NULL CHECK (I_IsImported IN ('Y','N')), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), IsPrintedSample CHAR(1) DEFAULT 'N' CHECK (IsPrintedSample IN ('Y','N')), M_Product_ID NUMERIC(10) DEFAULT NULL , M_Shipper_ID NUMERIC(10) DEFAULT NULL , OperationType CHAR(3) NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), ReferenceNo VARCHAR(60) DEFAULT NULL , TrailerPlate VARCHAR(60) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_EntryTicket_Key PRIMARY KEY (FTA_EntryTicket_ID))
;

-- Aug 22, 2014 11:24:17 AM VET
-- FTA
CREATE TABLE FTA_EntryTicketGuide (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , Ext_Guide VARCHAR(60) DEFAULT NULL , FTA_EntryTicketGuide_ID NUMERIC(10) NOT NULL, FTA_EntryTicket_ID NUMERIC(10) DEFAULT NULL , FTA_MobilizationGuide_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_EntryTicketGuide_Key PRIMARY KEY (FTA_EntryTicketGuide_ID))
;

-- Aug 22, 2014 11:24:22 AM VET
-- FTA
CREATE TABLE FTA_Fact (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, FTA_CreditDefinitionLine_ID NUMERIC(10) NOT NULL, FTA_Fact_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCreditFactManual CHAR(1) DEFAULT NULL CHECK (IsCreditFactManual IN ('Y','N')), Line_ID NUMERIC(10) DEFAULT NULL , Multiplier NUMERIC DEFAULT NULL , Record_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Fact_Key PRIMARY KEY (FTA_Fact_ID))
;

-- Aug 22, 2014 11:24:28 AM VET
-- FTA
CREATE TABLE FTA_Farm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_BPartner_Location_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FarmType CHAR(1) NOT NULL, FrontierEast VARCHAR(255) DEFAULT NULL , FrontierNorth VARCHAR(255) DEFAULT NULL , FrontierSouth VARCHAR(255) DEFAULT NULL , FrontierWest VARCHAR(255) DEFAULT NULL , FTA_Farm_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsDefault CHAR(1) DEFAULT 'N' CHECK (IsDefault IN ('Y','N')), IsValid CHAR(1) CHECK (IsValid IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Farm_Key PRIMARY KEY (FTA_Farm_ID))
;

-- Aug 22, 2014 11:24:34 AM VET
-- FTA
CREATE TABLE FTA_FarmDivision (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMERIC NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_Farm_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmDivision_Key PRIMARY KEY (FTA_FarmDivision_ID))
;

-- Aug 22, 2014 11:24:40 AM VET
-- FTA
CREATE TABLE FTA_FarmerCredit (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, AmtFarming NUMERIC DEFAULT NULL , ApprovedAmt NUMERIC DEFAULT NULL , ApprovedQty NUMERIC DEFAULT NULL , BasedOnEffectiveQuantity CHAR(1) DEFAULT NULL CHECK (BasedOnEffectiveQuantity IN ('Y','N')), Beneficiary_ID NUMERIC(10) DEFAULT NULL , C_BPartner_ID NUMERIC(10) NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, C_PaymentTerm_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CreditType CHAR(1) NOT NULL, C_UOM_ID NUMERIC(10) DEFAULT NULL , DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , EffectiveQty NUMERIC DEFAULT NULL , FarmingAlloc CHAR(1) DEFAULT NULL , FTA_CreditAct_ID NUMERIC(10) DEFAULT NULL , FTA_CreditDefinition_ID NUMERIC(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, GenerateBillOfEx CHAR(1) DEFAULT NULL , GenerateOrder CHAR(1) DEFAULT 'N', IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) CHECK (IsApproved IN ('Y','N')) NOT NULL, IsBillOfExchangeDocBased CHAR(1) DEFAULT 'N' CHECK (IsBillOfExchangeDocBased IN ('Y','N')), IsManagesPaymentProgram CHAR(1) DEFAULT 'N' CHECK (IsManagesPaymentProgram IN ('Y','N')), IsManual CHAR(1) DEFAULT 'N' CHECK (IsManual IN ('Y','N')), IsPayScheduleValid CHAR(1) DEFAULT 'N' CHECK (IsPayScheduleValid IN ('Y','N')), M_Product_ID NUMERIC(10) DEFAULT NULL , Parent_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , PreviousAmt NUMERIC DEFAULT NULL , PreviousApprovedAmt NUMERIC DEFAULT 0, PreviousApprovedQty NUMERIC DEFAULT 0, PreviousQty NUMERIC DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Qty NUMERIC NOT NULL, QtyFarming NUMERIC DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmerCredit_Key PRIMARY KEY (FTA_FarmerCredit_ID))
;

-- Aug 22, 2014 11:24:50 AM VET
-- FTA
CREATE TABLE FTA_FarmerLiquidation (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amt NUMERIC NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_ConversionType_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , FTA_CategoryCalc_ID NUMERIC(10) DEFAULT NULL , FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, FTA_FarmerLiquidation_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, NetWeight NUMERIC NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmerLiquidation_Key PRIMARY KEY (FTA_FarmerLiquidation_ID))
;

-- Aug 22, 2014 11:24:55 AM VET
-- FTA
CREATE TABLE FTA_FarmerLiquidationLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_FarmerLiquidation_ID NUMERIC(10) NOT NULL, FTA_FarmerLiquidationLine_ID NUMERIC(10) NOT NULL, FTA_RecordWeight_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LineNetAmt NUMERIC DEFAULT NULL , NetWeight NUMERIC NOT NULL, PayWeight NUMERIC NOT NULL, Price NUMERIC NOT NULL, PriceList NUMERIC DEFAULT NULL , Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, QualityAnalysis_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FarmerLiquidationLine_Key PRIMARY KEY (FTA_FarmerLiquidationLine_ID))
;

-- Aug 22, 2014 11:25:02 AM VET
-- FTA
CREATE TABLE FTA_Farming (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Area NUMERIC NOT NULL, Category_ID NUMERIC(10) NOT NULL, C_OrderLine_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EffectiveArea NUMERIC DEFAULT NULL , EstimatedDate TIMESTAMP DEFAULT NULL , EstimatedQty NUMERIC DEFAULT NULL , EstimatedYield NUMERIC DEFAULT NULL , FarmingValidate CHAR(1) DEFAULT NULL , FinancingType CHAR(1) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) DEFAULT NULL , FTA_Farming_ID NUMERIC(10) NOT NULL, GuideGenerate CHAR(1) DEFAULT NULL , HarvestEndDate TIMESTAMP DEFAULT NULL , HarvestStartDate TIMESTAMP DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) DEFAULT NULL CHECK (IsValid IN ('Y','N')), MaxQty NUMERIC DEFAULT NULL , PlantingCycle_ID NUMERIC(10) NOT NULL, PlantingEndDate TIMESTAMP DEFAULT NULL , PlantingStartDate TIMESTAMP DEFAULT NULL , Qty NUMERIC DEFAULT NULL , Re_EstimatedQty NUMERIC DEFAULT NULL , StartDate TIMESTAMP NOT NULL, Status CHAR(1) DEFAULT 'M' NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_Farming_Key PRIMARY KEY (FTA_Farming_ID))
;

-- Aug 22, 2014 11:25:07 AM VET
-- FTA
CREATE TABLE FTA_FarmingStage (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Category_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DayFrom NUMERIC NOT NULL, DayTo NUMERIC NOT NULL, FTA_FarmingStage_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) DEFAULT NULL , CONSTRAINT FTA_FarmingStage_Key PRIMARY KEY (FTA_FarmingStage_ID))
;

-- Aug 22, 2014 11:25:13 AM VET
-- FTA
CREATE TABLE FTA_FC_PaySchedule (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_PaySchedule_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DiscountAmt NUMERIC NOT NULL, DiscountDate TIMESTAMP NOT NULL, DueAmt NUMERIC NOT NULL, DueDate TIMESTAMP NOT NULL, FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, FTA_FC_PaySchedule_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) DEFAULT 'N' CHECK (IsValid IN ('Y','N')), Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_FC_PaySchedule_Key PRIMARY KEY (FTA_FC_PaySchedule_ID))
;

-- Aug 22, 2014 11:25:19 AM VET
-- FTA
CREATE TABLE FTA_InterestRate (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_InterestRate_ID NUMERIC(10) NOT NULL, FTA_InterestType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Rate NUMERIC NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValidFrom TIMESTAMP NOT NULL, CONSTRAINT FTA_InterestRate_Key PRIMARY KEY (FTA_InterestRate_ID))
;

-- Aug 22, 2014 11:25:25 AM VET
-- FTA
CREATE TABLE FTA_InterestType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, CalculationType CHAR(1) DEFAULT 'C' NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_DocTypeTarget_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DaysDue NUMERIC(10) DEFAULT NULL , DaysFixed CHAR(1) DEFAULT 'Y' CHECK (DaysFixed IN ('Y','N')), FTA_InterestType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, RateFixed CHAR(1) DEFAULT 'Y' CHECK (RateFixed IN ('Y','N')), Type VARCHAR(2) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, CONSTRAINT FTA_InterestType_Key PRIMARY KEY (FTA_InterestType_ID))
;

-- Aug 22, 2014 11:26:16 AM VET
-- FTA
CREATE TABLE FTA_MobilizationGuide (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_OrgTrx_ID NUMERIC(10) DEFAULT NULL , C_BPartner_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(30) NOT NULL, Ext_Guide VARCHAR(60) DEFAULT NULL , FTA_Farming_ID NUMERIC(10) DEFAULT NULL , FTA_LoadOrder_ID NUMERIC(10) DEFAULT NULL , FTA_MobilizationGuide_ID NUMERIC(10) NOT NULL, FTA_RecordWeight_ID NUMERIC(10) DEFAULT NULL , FTA_VehicleType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsSOTrx CHAR(1) DEFAULT 'N' CHECK (IsSOTrx IN ('Y','N')), M_Warehouse_ID NUMERIC(10) DEFAULT NULL , Owner_ID NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), QtyToDeliver NUMERIC NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValidTo TIMESTAMP DEFAULT NULL , CONSTRAINT FTA_MobilizationGuide_Key PRIMARY KEY (FTA_MobilizationGuide_ID))
;

-- Aug 22, 2014 11:26:22 AM VET
-- FTA
CREATE TABLE FTA_ObservationType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_ObservationType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, CONSTRAINT FTA_ObservationType_Key PRIMARY KEY (FTA_ObservationType_ID))
;

-- Aug 22, 2014 11:26:28 AM VET
-- FTA
CREATE TABLE FTA_PaymentRequest (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_BP_BankAccount_ID NUMERIC(10) DEFAULT NULL , C_Charge_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, C_Invoice_ID NUMERIC(10) DEFAULT NULL , C_PaySelectionCheck_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(30) DEFAULT NULL , FTA_FarmerCredit_ID NUMERIC(10) NOT NULL, FTA_FarmerLiquidation_ID NUMERIC(10) DEFAULT NULL , FTA_PaymentRequest_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, PayAmt NUMERIC NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_PaymentRequest_Key PRIMARY KEY (FTA_PaymentRequest_ID))
;

-- Aug 22, 2014 11:26:34 AM VET
-- FTA
CREATE TABLE FTA_ProductListApproved (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, ApprovedQty NUMERIC NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CreditDefinition_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Substitute_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_ProductListApproved_Key PRIMARY KEY (FTA_CreditDefinition_ID, M_Product_ID))
;

-- Aug 22, 2014 11:26:39 AM VET
-- FTA
CREATE TABLE FTA_ProductsToApply (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, DateFrom TIMESTAMP DEFAULT NULL , DateTo TIMESTAMP DEFAULT NULL , Dosage_Uom_ID NUMERIC(10) NOT NULL, FTA_ProductsToApply_ID NUMERIC(10) NOT NULL, FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, FTA_TechnicalFormLine_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, M_Warehouse_ID NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Qty NUMERIC NOT NULL, QtyDosage NUMERIC NOT NULL, QtySuggested NUMERIC DEFAULT NULL , Suggested_Uom_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_ProductsToApply_Key PRIMARY KEY (FTA_ProductsToApply_ID))
;

-- Aug 22, 2014 11:26:44 AM VET
-- FTA
CREATE TABLE FTA_QualityAnalysis (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AnalysisType VARCHAR(2) DEFAULT 'QA' NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus VARCHAR(2) DEFAULT 'DR', DocumentNo VARCHAR(60) DEFAULT NULL , DocumentPrint CHAR(1) DEFAULT NULL , FTA_Chute_ID NUMERIC(10) DEFAULT NULL , FTA_EntryTicket_ID NUMERIC(10) NOT NULL, FTA_QualityAnalysis_ID NUMERIC(10) NOT NULL, FTA_RecordWeight_ID NUMERIC(10) DEFAULT NULL , I_IsImported CHAR(1) DEFAULT NULL CHECK (I_IsImported IN ('Y','N')), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), M_Product_ID NUMERIC(10) DEFAULT NULL , OperationType VARCHAR(3) NOT NULL, Orig_QualityAnalysis_ID NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), ProductStatus CHAR(1) DEFAULT 'A' NOT NULL, QualityAnalysis_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_QualityAnalysis_Key PRIMARY KEY (FTA_QualityAnalysis_ID))
;

-- Aug 22, 2014 11:26:50 AM VET
-- FTA
CREATE TABLE FTA_ReceptionCapacity (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_ReceptionCapacity_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Warehouse_ID NUMERIC(10) NOT NULL, Qty NUMERIC NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValidFrom TIMESTAMP NOT NULL, CONSTRAINT FTA_ReceptionCapacity_Key PRIMARY KEY (FTA_ReceptionCapacity_ID))
;

-- Aug 22, 2014 11:26:56 AM VET
-- FTA
CREATE TABLE FTA_RecordWeight (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CreateFrom CHAR(1) DEFAULT NULL , C_UOM_ID NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , DocumentPrint CHAR(1) DEFAULT NULL , FTA_Chute_ID NUMERIC(10) DEFAULT NULL , FTA_EntryTicket_ID NUMERIC(10) NOT NULL, FTA_LoadOrder_ID NUMERIC(10) DEFAULT NULL , FTA_QualityAnalysis_ID NUMERIC(10) DEFAULT NULL , FTA_RecordWeight_ID NUMERIC(10) NOT NULL, GrossWeight NUMERIC NOT NULL, I_IsImported CHAR(1) DEFAULT NULL CHECK (I_IsImported IN ('Y','N')), ImportWeight NUMERIC DEFAULT NULL , InDate TIMESTAMP DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsPrinted CHAR(1) DEFAULT 'N' CHECK (IsPrinted IN ('Y','N')), IsSOTrx CHAR(1) CHECK (IsSOTrx IN ('Y','N')) NOT NULL, M_Product_ID NUMERIC(10) DEFAULT NULL , M_ProductionLine_ID NUMERIC(10) DEFAULT NULL , NetWeight NUMERIC NOT NULL, OperationType VARCHAR(3) NOT NULL, OutDate TIMESTAMP DEFAULT NULL , PayWeight NUMERIC DEFAULT NULL , Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1) DEFAULT NULL , SelectionWeight CHAR(1) DEFAULT 'P', TareWeight NUMERIC NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WeightStatus CHAR(1) DEFAULT 'T', CONSTRAINT FTA_RecordWeight_Key PRIMARY KEY (FTA_RecordWeight_ID))
;

-- Aug 22, 2014 11:27:02 AM VET
-- FTA
CREATE TABLE FTA_RecordWeightDetail (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_CategoryCalc_ID NUMERIC(10) NOT NULL, FTA_RecordWeight_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Line NUMERIC(10) DEFAULT NULL , Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Weight NUMERIC NOT NULL, CONSTRAINT FTA_RecordWeightDetail_Key PRIMARY KEY (FTA_CategoryCalc_ID, FTA_RecordWeight_ID))
;

-- Aug 22, 2014 11:27:09 AM VET
-- FTA
CREATE TABLE FTA_SuggestedProduct (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Category_ID NUMERIC(10) DEFAULT NULL , Comments VARCHAR(255) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DayFrom NUMERIC DEFAULT NULL , DayTo NUMERIC DEFAULT NULL , Dosage_Uom_ID NUMERIC(10) DEFAULT NULL , FTA_FarmingStage_ID NUMERIC(10) DEFAULT NULL , FTA_ObservationType_ID NUMERIC(10) DEFAULT NULL , FTA_SuggestedProduct_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, QtyDosage NUMERIC DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_SuggestedProduct_Key PRIMARY KEY (FTA_SuggestedProduct_ID))
;

-- Aug 22, 2014 11:27:16 AM VET
-- FTA
CREATE TABLE FTA_TechnicalForm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO', DocStatus VARCHAR(2) DEFAULT 'DR', DocumentNo VARCHAR(60) DEFAULT NULL , FTA_Farm_ID NUMERIC(10) DEFAULT NULL , FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, GenerateOrder CHAR(1) DEFAULT 'N', IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, SalesRep_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_TechnicalForm_Key PRIMARY KEY (FTA_TechnicalForm_ID))
;

-- Aug 22, 2014 11:27:23 AM VET
-- FTA
CREATE TABLE FTA_TechnicalFormLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FTA_FarmDivision_ID NUMERIC(10) NOT NULL, FTA_Farm_ID NUMERIC(10) NOT NULL, FTA_Farming_ID NUMERIC(10) NOT NULL, FTA_FarmingStage_ID NUMERIC(10) NOT NULL, FTA_ObservationType_ID NUMERIC(10) NOT NULL, FTA_TechnicalForm_ID NUMERIC(10) NOT NULL, FTA_TechnicalFormLine_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT NULL CHECK (Processed IN ('Y','N')), Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_TechnicalFormLine_Key PRIMARY KEY (FTA_TechnicalFormLine_ID))
;

-- Aug 22, 2014 11:27:30 AM VET
-- FTA
CREATE TABLE FTA_Vehicle (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMERIC(10) DEFAULT NULL , FTA_Vehicle_ID NUMERIC(10) NOT NULL, FTA_VehicleModel_ID NUMERIC(10) DEFAULT NULL , FTA_VehicleType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LoadCapacity NUMERIC NOT NULL, MinLoadCapacity NUMERIC DEFAULT NULL , MinVolumeCapacity NUMERIC DEFAULT NULL , M_Shipper_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, VehiclePlate VARCHAR(60) NOT NULL, VolumeCapacity NUMERIC NOT NULL, CONSTRAINT FTA_Vehicle_Key PRIMARY KEY (FTA_Vehicle_ID))
;

-- Aug 22, 2014 11:27:37 AM VET
-- FTA
CREATE TABLE FTA_VehicleBrand (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_VehicleBrand_Key PRIMARY KEY (FTA_VehicleBrand_ID))
;

-- Aug 22, 2014 11:27:45 AM VET
-- FTA
CREATE TABLE FTA_VehicleModel (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_VehicleBrand_ID NUMERIC(10) NOT NULL, FTA_VehicleModel_ID NUMERIC(10) NOT NULL, FTA_VehicleType_ID NUMERIC(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT FTA_VehicleModel_Key PRIMARY KEY (FTA_VehicleModel_ID))
;

-- Aug 22, 2014 11:27:52 AM VET
-- FTA
CREATE TABLE FTA_VehicleType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FTA_VehicleType_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LoadCapacity NUMERIC NOT NULL, MinLoadCapacity NUMERIC DEFAULT NULL , MinVolumeCapacity NUMERIC DEFAULT NULL , Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(60) NOT NULL, VolumeCapacity NUMERIC NOT NULL, CONSTRAINT FTA_VehicleType_Key PRIMARY KEY (FTA_VehicleType_ID))
;

-- Aug 25, 2014 4:58:44 AM VET
-- FTA
CREATE TABLE FTA_LoadOrder (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_DocType_ID NUMERIC(10) NOT NULL, ConfirmedWeight NUMERIC DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_Volume_ID NUMERIC(10) NOT NULL, C_UOM_Weight_ID NUMERIC(10) NOT NULL, DateDoc TIMESTAMP NOT NULL, DeliveryRule CHAR(1) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , DocAction CHAR(2) DEFAULT 'CO' NOT NULL, DocStatus VARCHAR(2) DEFAULT 'DR' NOT NULL, DocumentNo VARCHAR(60) DEFAULT NULL , FTA_Driver_ID NUMERIC(10) DEFAULT NULL , FTA_EntryTicket_ID NUMERIC(10) NOT NULL, FTA_LoadOrder_ID NUMERIC(10) NOT NULL, FTA_Vehicle_ID NUMERIC(10) DEFAULT NULL , FTA_VehicleType_ID NUMERIC(10) NOT NULL, InvoiceRule CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsApproved CHAR(1) DEFAULT 'N' CHECK (IsApproved IN ('Y','N')) NOT NULL, IsDelivered CHAR(1) DEFAULT 'N' CHECK (IsDelivered IN ('Y','N')), IsHandleRecordWeight CHAR(1) DEFAULT NULL CHECK (IsHandleRecordWeight IN ('Y','N')), IsInvoiced CHAR(1) DEFAULT 'N' CHECK (IsInvoiced IN ('Y','N')), IsMoved CHAR(1) DEFAULT 'N' CHECK (IsMoved IN ('Y','N')), IsWeightRegister CHAR(1) DEFAULT 'N' CHECK (IsWeightRegister IN ('Y','N')), LoadCapacity NUMERIC NOT NULL, M_Product_ID NUMERIC(10) DEFAULT NULL , M_Shipper_ID NUMERIC(10) DEFAULT NULL , M_Warehouse_ID NUMERIC(10) DEFAULT NULL , OperationType VARCHAR(3) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1) DEFAULT NULL , ShipDate TIMESTAMP DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Volume NUMERIC DEFAULT NULL , VolumeCapacity NUMERIC DEFAULT NULL , Weight NUMERIC DEFAULT NULL , CONSTRAINT FTA_LoadOrder_Key PRIMARY KEY (FTA_LoadOrder_ID))
;

-- Aug 25, 2014 4:58:51 AM VET
-- FTA
CREATE TABLE FTA_LoadOrderLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_InvoiceLine_ID NUMERIC(10) DEFAULT NULL , ConfirmedQty NUMERIC DEFAULT NULL , ConfirmedWeight NUMERIC DEFAULT NULL , C_OrderLine_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DD_OrderLine_ID NUMERIC(10) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , FTA_LoadOrder_ID NUMERIC(10) NOT NULL, FTA_LoadOrderLine_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_InOutLine_ID NUMERIC(10) DEFAULT NULL , M_MovementLine_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')), Qty NUMERIC NOT NULL, SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Volume NUMERIC NOT NULL, Weight NUMERIC NOT NULL, CONSTRAINT FTA_LoadOrderLine_Key PRIMARY KEY (FTA_LoadOrderLine_ID))
;


