ALTER TABLE FTA_MobilizationGuide ADD CONSTRAINT FK_MobilizationGuide_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_MobilizationGuide ADD CONSTRAINT FK_MobilizationGuide_Farming FOREIGN KEY (FTA_Farming_ID)
REFERENCES FTA_Farming (FTA_Farming_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_MobilizationGuide ADD CONSTRAINT FK_MobilizationGuide_VehicleType FOREIGN KEY (FTA_VehicleType_ID)
REFERENCES FTA_VehicleType (FTA_VehicleType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_MobilizationGuide ADD CONSTRAINT FK_MobilizationGuide_Warehouse FOREIGN KEY (M_Warehouse_ID)
REFERENCES M_Warehouse (M_Warehouse_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_MobilizationGuide ADD CONSTRAINT FK_MobilizationGuide_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_Farm ADD CONSTRAINT FK_Farm_BPartnerLocation FOREIGN KEY (C_BPartner_Location_ID)
REFERENCES C_BPartner_Location (C_BPartner_Location_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_Farm ADD CONSTRAINT FK_Farm_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmDivision ADD CONSTRAINT FK_FarmDivision_Farm FOREIGN KEY (FTA_Farm_ID)
REFERENCES FTA_Farm (FTA_Farm_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_Farming ADD CONSTRAINT FK_Farming_FarmDivision FOREIGN KEY (FTA_FarmDivision_ID)
REFERENCES FTA_FarmDivision (FTA_FarmDivision_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_Farming ADD CONSTRAINT FK_Farming_FarmerCredit FOREIGN KEY (FTA_FarmerCredit_ID)
REFERENCES FTA_FarmerCredit (FTA_FarmerCredit_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_SuggestedProduct ADD CONSTRAINT FK_SuggestedProduct_FarmingStage FOREIGN KEY (FTA_FarmingStage_ID)
REFERENCES FTA_FarmingStage (FTA_FarmingStage_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_SuggestedProduct ADD CONSTRAINT FK_SuggestedProduct_ObservationType FOREIGN KEY (FTA_ObservationType_ID)
REFERENCES FTA_ObservationType (FTA_ObservationType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_SuggestedProduct ADD CONSTRAINT FK_SuggestedProduct_ProductCategory FOREIGN KEY (M_Product_Category_ID)
REFERENCES M_Product_Category (M_Product_Category_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_SuggestedProduct ADD CONSTRAINT FK_SuggestedProduct_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalForm ADD CONSTRAINT FK_TechnicalForm_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalForm ADD CONSTRAINT FK_TechnicalForm_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalForm ADD CONSTRAINT FK_TechnicalForm_Farm FOREIGN KEY (FTA_Farm_ID)
REFERENCES FTA_Farm (FTA_Farm_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalFormLine ADD CONSTRAINT FK_TechnicalFormLine_FarmDivision FOREIGN KEY (FTA_FarmDivision_ID)
REFERENCES FTA_FarmDivision (FTA_FarmDivision_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalFormLine ADD CONSTRAINT FK_TechnicalFormLine_Farming FOREIGN KEY (FTA_Farming_ID)
REFERENCES FTA_Farming (FTA_Farming_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalFormLine ADD CONSTRAINT FK_TechnicalFormLine_FarmingStage FOREIGN KEY (FTA_FarmingStage_ID)
REFERENCES FTA_FarmingStage (FTA_FarmingStage_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalFormLine ADD CONSTRAINT FK_TechnicalFormLine_ObservationType FOREIGN KEY (FTA_ObservationType_ID)
REFERENCES FTA_ObservationType (FTA_ObservationType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_TechnicalFormLine ADD CONSTRAINT FK_TechnicalFormLine_TechnicalForm FOREIGN KEY (FTA_TechnicalForm_ID)
REFERENCES FTA_TechnicalForm (FTA_TechnicalForm_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_ProductsToApply ADD CONSTRAINT FK_ProductsToApply_TecnicalForm FOREIGN KEY (FTA_TechnicalForm_ID)
REFERENCES FTA_TechnicalForm (FTA_TechnicalForm_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_ProductsToApply ADD CONSTRAINT FK_ProductsToApply_TecnicalFormLine FOREIGN KEY (FTA_TechnicalFormLine_ID)
REFERENCES FTA_TechnicalFormLine (FTA_TechnicalFormLine_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_ProductsToApply ADD CONSTRAINT FK_ProductsToApply_Uom FOREIGN KEY (C_Uom_ID)
REFERENCES C_Uom (C_Uom_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_ProductsToApply ADD CONSTRAINT FK_ProductsToApply_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_BussinesPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_MobilizationGuide FOREIGN KEY (FTA_MobilizationGuide_ID)
REFERENCES FTA_MobilizationGuide (FTA_MobilizationGuide_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_QualityAnalysis  ADD CONSTRAINT FK_QualityAnalysis_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_QualityAnalysis ADD CONSTRAINT FK_QualityAnalysis_EntryTicket FOREIGN KEY (FTA_EntryTicket_ID)
REFERENCES FTA_EntryTicket (FTA_EntryTicket_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_QualityAnalysis ADD CONSTRAINT FK_QualityAnalysis_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_QualityAnalysis ADD CONSTRAINT FK_QualityAnalysis_Attribute FOREIGN KEY (QualityAnalysis_ID)
REFERENCES M_AttributeSetInstance (M_AttributeSetInstance_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_RecordWeight ADD CONSTRAINT FK_RecordWeight_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_RecordWeight ADD CONSTRAINT FK_RecordWeight_Uom FOREIGN KEY (C_Uom_ID)
REFERENCES C_Uom (C_Uom_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_RecordWeight ADD CONSTRAINT FK_RecordWeight_EntryTicket FOREIGN KEY (FTA_EntryTicket_ID)
REFERENCES FTA_EntryTicket (FTA_EntryTicket_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_RecordWeight ADD CONSTRAINT FK_RecordWeight_QualityAnalysis FOREIGN KEY (FTA_QualityAnalysis_ID)
REFERENCES FTA_QualityAnalysis (FTA_QualityAnalysis_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_RecordWeight ADD CONSTRAINT FK_RecordWeight_InOut FOREIGN KEY (M_InOut_ID)
REFERENCES M_InOut (M_InOut_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_CreditDefinition ADD CONSTRAINT FK_CreditDefinition_Lot  FOREIGN KEY (PlantingCycle_ID)
REFERENCES M_Lot (M_Lot_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_CreditDefinition ADD CONSTRAINT FK_CreditDefinition_CategoryFOREIGN KEY (Category_ID)
REFERENCES M_Product (M_Product_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_CreditDefinition ADD CONSTRAINT FK_CreditDefinition_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_CreditDefinition ADD CONSTRAINT FK_CreditDefinition_PriceList FOREIGN KEY (M_PriceList_ID)
REFERENCES M_PriceList (M_PriceList_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_CreditDefinition ADD CONSTRAINT FK_CreditDefinition_PlantingCycle FOREIGN KEY (M_Lot_ID)
REFERENCES M_Lot (M_Lot_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;



ALTER TABLE FTA_CreditDefinitionLine ADD CONSTRAINT FK_CreditDefinitionLine_CreditDefinition  FOREIGN KEY (FTA_CreditDefinition_ID)
REFERENCES FTA_CreditDefinition (FTA_CreditDefinition_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_CreditDefinitionLine ADD CONSTRAINT FK_CreditDefinitionLine_Product_Category  FOREIGN KEY (M_Product_Category_ID)
REFERENCES M_Product_Category (M_Product_Category_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_CreditDefinitionLine ADD CONSTRAINT FK_CreditDefinitionLine_Product  FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_CreditDefinitionLine ADD CONSTRAINT FK_CreditDefinitionLine_Charge FOREIGN KEY (C_Charge_ID)
REFERENCES C_Charge (C_Charge_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_CreditDefinitionLine ADD CONSTRAINT FK_CreditDefinitionLine_Uom FOREIGN KEY (C_Uom_ID)
REFERENCES C_Uom (C_Uom_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_BPartnerBeneficiary  FOREIGN KEY (Beneficiary_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_BPartner  FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_Charge  FOREIGN KEY (C_Charge_ID)
REFERENCES C_Charge (C_Charge_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_DocType  FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_Order  FOREIGN KEY (C_Order_ID)
REFERENCES C_Order (C_Order_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_Uom  FOREIGN KEY (C_Uom_ID)
REFERENCES C_Uom (C_Uom_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerCredit ADD CONSTRAINT FK_FarmerCredit_CreditDefinition  FOREIGN KEY (FTA_CreditDefinition_ID)
REFERENCES FTA_CreditDefinition (FTA_CreditDefinition_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_Allocation ADD CONSTRAINT FK_Allocation_FarmerCredit FOREIGN KEY (FTA_FarmerCreditLine_ID)
REFERENCES FTA_FarmerCreditLine (FTA_FarmerCreditLine_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_CashLine FOREIGN KEY (C_CashLine_ID)
REFERENCES C_CashLine (C_CashLine_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_Invoice FOREIGN KEY (C_Invoice_ID)
REFERENCES C_Invoice (C_Invoice_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_Order FOREIGN KEY (C_Order_ID)
REFERENCES C_Order (C_Order_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_Payment FOREIGN KEY (C_Payment_ID)
REFERENCES C_Payment (C_Payment_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_AllocationLine ADD CONSTRAINT FK_AllocationLine_Allocation FOREIGN KEY (FTA_Allocation_ID)
REFERENCES FTA_Allocation (FTA_Allocation_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_CategoryCalc ADD CONSTRAINT FK_CategoryCalc_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_EntryTicket ADD CONSTRAINT FK_EntryTicket_MovilizationGuide FOREIGN KEY (FTA_MobilizationGuide_ID)
REFERENCES FTA_MobilizationGuide (FTA_MobilizationGuide_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerLiquidation ADD CONSTRAINT FK_FarmerLiquidation_BPartner FOREIGN KEY (C_BPartner_ID)
REFERENCES C_BPartner (C_BPartner_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerLiquidation ADD CONSTRAINT FK_FarmerLiquidation_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType (C_DocType_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerLiquidation ADD CONSTRAINT FK_FarmerLiquidation_Invoice FOREIGN KEY (C_Invoice_ID)
REFERENCES C_Invoice (C_Invoice_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerLiquidation ADD CONSTRAINT FK_FarmerLiquidation_FarmerCredit FOREIGN KEY (FTA_FarmerCredit_ID)
REFERENCES FTA_FarmerCredit (FTA_FarmerCredit_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerLiquidation ADD CONSTRAINT FK_FarmerLiquidation_Product FOREIGN KEY (M_Product_ID)
REFERENCES M_Product (M_Product_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerLiquidationLine ADD CONSTRAINT FK_FarmerLiquidationLine_CategoryCalc FOREIGN KEY (FTA_CategoryCalc_ID)
REFERENCES FTA_CategoryCalc (FTA_CategoryCalc_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;


ALTER TABLE FTA_FarmerLiquidationLine ADD CONSTRAINT FK_FarmerLiquidationLine_FarmerLiquidation FOREIGN KEY (FTA_FarmerLiquidation_ID)
REFERENCES FTA_FarmerLiquidation (FTA_FarmerLiquidation_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE FTA_FarmerLiquidationLine ADD CONSTRAINT FK_FarmerLiquidationLine_RecordWeight FOREIGN KEY (FTA_RecordWeight_ID)
REFERENCES FTA_RecordWeight (FTA_RecordWeight_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;



ALTER TABLE FTA_ReceptionCapacity ADD CONSTRAINT FK_ReceptionCapacity_WareHouse FOREIGN KEY (M_WareHouse_ID)
REFERENCES M_WareHouse (M_WareHouse_ID)
ON UPDATE CASCADE 
ON DELETE RESTRICT;



